name: global_sos

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.8.1

dependencies:
  country_flags: ^3.3.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_localizations:
    sdk: flutter
  hooks_riverpod: ^3.0.0-dev.16
  intl: any
  riverpod_annotation: ^3.0.0-dev.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.0-dev.16
  build_runner: ^2.5.4
  custom_lint: ^0.7.6
  riverpod_lint: ^3.0.0-dev.16

flutter:
  generate: true
  uses-material-design: true